environment:
  access_token: V7hA4MtHW/PDJ1CkwzQYPFEihapq83bHxz7jiAVdHuDJSWuZkXe3VaTSPahdZ9eo
image: Visual Studio 2017
configuration: Release
init:
# Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
# Install repo specific stuff here
before_build:
# Display .NET Core version
  - cmd: dotnet --version
# Display minimal restore text
  - cmd: dotnet restore ./GreenUtil.sln --verbosity m
  - choco install opencover.portable
  - choco install codecov
test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\projects\greenutil\GreenUtil.Test\bin\Release\GreenUtil.Test.dll" -output:".\coverage.xml" -log:Info -filter:"+[GreenUtil*]* -[GreenUtil.Test]* -[GreenUtil]*Designer.cs"
after_test:
   - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 5fca849b-5826-42b1-bcef-3b752abee426
artifacts:
  - path: '.\GreenUtil\bin\Release\netstandard2.0\GreenUtil.dll'
    name: GreenUtil.dll
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: lKS7OIfKrf8/DWa+zPE7338BWZSkCn06LynccKNlqKzTHzDOaXfbCtS6OOV40Kz8
  artifact: /.*\.nupkg/
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "leandro.ltavares@gmail.com"
  - git config --global user.name "Leandro Luciani Tavares"
  - git clone --branch=master https://github.com/leandroltavares/GreenUtil.wiki.git C:\projects\wiki
  - cmd: C:\projects\greenutil\Assets\MarkdownGenerator.exe C:\projects\greenutil\GreenUtil\bin\Release\net471\GreenUtil.dll C:\projects\wiki
  - git cd C:\projects\wiki
  - git add .
  - git commit -m "Commiting wiki changes"
  - git push origin HEAD:master
  