environment:
  access_token:
    secure: OPLBHeZzL5ATezLrF5TsKxpc7JhhzvOne7E9MyxfNHafNf9aKiIUbr/mRcuvqHQU
image: Visual Studio 2017
configuration: Release
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
# Install repo specific stuff here
before_build:
# Display .NET Core version
  - cmd: dotnet --version
# Display minimal restore text
  - cmd: dotnet restore ./GreenUtil.sln --verbosity m
  #- choco install opencover.portable
  #- choco install codecov
#test_script:
 # - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\projects\greenutil\GreenUtil.Test\bin\Release\GreenUtil.Test.dll" -output:".\coverage.xml" -log:Info -filter:"+[GreenUtil*]* -[GreenUtil.Test]* -[GreenUtil]*Designer.cs"
#after_test:
 #  - ps: |
  #    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
   #   Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    #  bash codecov.sh -f "coverage.xml" -t 5fca849b-5826-42b1-bcef-3b752abee426
#artifacts:
 # - path: '.\GreenUtil\bin\Release\netstandard2.0\GreenUtil.dll'
  #  name: GreenUtil.dll
  #- path: '**\*.nupkg'
#deploy:
 # provider: NuGet
 # api_key:
  #  secure: lKS7OIfKrf8/DWa+zPE7338BWZSkCn06LynccKNlqKzTHzDOaXfbCtS6OOV40Kz8
 # artifact: /.*\.nupkg/
on_success:
  #- ps: Start-Sleep -s 3600
  - ps: Write-Host "Waiting"
  #- ps: Invoke-Expression -Command "C:\projects\greenutil\Assets\wiki.ps1 -token $($env:access_token)"
  - ps: |
      $mdFolder = "C:\projects\wiki2"

      Write-Host "Start publishing documentation to wiki"
      git config --global credential.helper store
      Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
      git config --global user.email "owenmcdonnell@appveyor.com"
      git config --global user.name "Owen McDonnell"
      Remove-Item $mdFolder -Force -Recurse -ErrorAction SilentlyContinue
      md $mdFolder
      cd $mdFolder

      git clone --branch=master "https://github.com/OwenMcDonnell/GreenUtil.wiki.git" -q
      cd GreenUtil.wiki

      git status
      #C:\projects\greenutil\Assets\MarkdownGenerator.exe "C:\projects\greenutil\GreenUtil\bin\Release\net471\GreenUtil.dll" "$($mdFolder)\GreenUtil.wiki"
      #git status
      Add-content "Home.md" "test content"
      git add .
      git status
      git commit -m "Commiting wiki changes"
      git status
      git push origin master
      git status
      Write-Host "Finish publishing documentation to wiki"
